name: Test strike-api

on: [push]

env:
  PYTHON_VERSION: "3.7"
  PACKAGE_FOLDER: strike_api
  TEST_FOLDER: tests
  COVERAGE_LIMIT: 90
    
jobs:
   build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry && poetry build
   code-quality:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry && poetry install
    - name: Check codestlye with Black
      - uses: actions/checkout@v2
      - uses: psf/black@stable
    
    - name: Security Analysis with bandit
      run: |
        mkdir ci-logs
        poetry run bandit -r -lll  -f txt -o ci-logs/bandit.log ${{env.PACKAGE_FOLDER}} ${{env.TEST_FOLDER}}
        
    - name: Archive bandit report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: ci-logs/bandit.log

   code-coverage:
    needs: code-quality
    runs-on: ubuntu-latest
    env:
      STRIKE_API_KEY: ${{ secrets.STRIKE_DEV_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry && poetry install

    - name: Test with pytest
      run: |
        poetry install
        poetry run pytest ${{env.TEST_FOLDER}}  --cov-report=xml --cov=${{env.PACKAGE_FOLDER}} --junitxml=./coverage.xml
    - name: Code Coverage Summary Report
      run: |
       pip install coverage
       coverage combine && coverage report --fail-under=${{env.COVERAGE_LIMIT}} -m
       coverage html 
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: htmlcov/index.html